apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: abekrenev-devops-final-task

images:
    - name: final-task
      newName: sashkevich4/abekrenev-devops-final-task
      newTag: v1.0.3

resources:
- namespace.yaml
- deployment.yaml
- service.yaml